# Generated by Django 3.0.4 on 2020-04-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('filename', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('stage', models.TextField(choices=[(1, 'Upload Building Data'), (2, 'Upload Half Hourly Data'), (3, 'Upload Meter Data')])),
                ('processed', models.BooleanField(default=False)),
                ('error', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('building_uid', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(default=0)),
                ('reading_date_time', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Meter')),
            ],
        ),
    ]
