# Generated by Django 3.0.4 on 2020-03-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='stage',
            field=models.TextField(choices=[(1, 'Upload Building Data'), (2, 'Upload Half Hourly Data'), (3, 'Upload Meter Data')], default=1),
            preserve_default=False,
        ),
    ]
