# Generated by Django 3.0.4 on 2020-03-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='error',
            field=models.NullBooleanField(default=None),
        ),
    ]
